# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: image
    displayName: Pool Image
    type: string
    default: 'windows-latest'
    values:
      - 'windows-latest'
      - 'ubuntu-latest'
      - 'macOS-latest'

trigger: none

pool:
  vmImage: ${{ parameters.image }}

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assemble'
    

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'jacocoTestReport'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/test/html'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.SourcesDirectory)'
    Contents: '**/Calculator*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '7de0b821-99e8-4560-9da7-cfcab40f60e2/439ece79-dce4-4e91-81e0-8f4810168827'
    vstsFeedPackagePublish: 'test'
    versionOption: 'minor'
    packagePublishDescription: 'This is sample application'
    verbosity: 'Debug'